### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Ben7124** [keithgmitchell/PUMA#2]
Hello,

I am using OS X. After I run pip install -r pip_requirements.txt, I got the following error:

ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.

Any help is much appreciated.

Thanks!

Ben

**Comment by keithgmitchell** [comment]
Try changing the last line in the pip_requirments.txt to urllib3==1.24 and that should fix the dependency issues. I will update this in the repository as well.
